services:
  postgres:
    image: postgres:14
    container_name: go-rest-base-db
    environment:
      POSTGRES_USER: afchamis
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: go-rest-base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge